# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vad.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tvad.proto\x12\x16\x63ropfresh.voice.vad.v1\"V\n\nAudioFrame\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08sequence\x18\x02 \x01(\x03\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\x12\r\n\x05pcm16\x18\x04 \x01(\x0c\"\x8d\x01\n\x08VadEvent\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x13\n\x0bprobability\x18\x03 \x01(\x02\x12\x0b\n\x03rms\x18\x04 \x01(\x02\x12\x12\n\nsegment_id\x18\x05 \x01(\t\x12\x10\n\x08sequence\x18\x06 \x01(\x03\x12\x16\n\x0e\x65nd_of_segment\x18\x07 \x01(\x08\x32h\n\x0bVadAnalyzer\x12Y\n\rAnalyzeStream\x12\".cropfresh.voice.vad.v1.AudioFrame\x1a .cropfresh.voice.vad.v1.VadEvent(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOFRAME']._serialized_start=37
  _globals['_AUDIOFRAME']._serialized_end=123
  _globals['_VADEVENT']._serialized_start=126
  _globals['_VADEVENT']._serialized_end=267
  _globals['_VADANALYZER']._serialized_start=269
  _globals['_VADANALYZER']._serialized_end=373
# @@protoc_insertion_point(module_scope)
